-- This script fills the table for the year 2025
INSERT INTO dim_date (date_key, day_num, day_name, week_num, month_num, month_name, quarter, year_num, is_weekend)
SELECT 
    datum AS date_key,
    DAYOFMONTH(datum) AS day_num,
    DAYNAME(datum) AS day_name,
    WEEK(datum) AS week_num,
    MONTH(datum) AS month_num,
    MONTHNAME(datum) AS month_name,
    QUARTER(datum) AS quarter,
    YEAR(datum) AS year_num,
    CASE WHEN DAYOFWEEK(datum) IN (1, 7) THEN 1 ELSE 0 END AS is_weekend
FROM ( 
    -- This subquery generates a list of 365 dates
    SELECT ADDDATE('2025-01-01', t4.i*10000 + t3.i*1000 + t2.i*100 + t1.i*10 + t0.i) AS datum
    FROM
        (SELECT 0 i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) t0,
        (SELECT 0 i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) t1,
        (SELECT 0 i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) t2,
        (SELECT 0 i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) t3,
        (SELECT 0 i UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) t4
) v
WHERE datum BETWEEN '2025-01-01' AND '2025-12-31'
ORDER BY datum;

SELECT *
FROM dim_date;nb  